firemodels/cfast

- CFAST/Source/cyl_conduct.f90
> pull change to fix problem addressed in issue 205

- Utilities/cfastbot/run_cfastbot.sh
> cfastbot: improve logic to keep multiple instances of cfastbot from running at the same time

- Source/CFAST/solve.f90
the cfast tech guide says that the problem being solved is:
f(t,y,y') = 0
where f(t,y,y') = y' - rhs of odes's for gas equations
and f(t,y,y') = q" + k*dT/dx for wall temperature equation
in the subroutine calculate_residuals variables are changed to
y_vector, yprime_vector and the variable associated with the residual function f is changed to f_vector
> change cfast program variable notation to be consistent with cfast tech guide

- Source/CFAST/cfast_data.f90
- Source/CFAST/cfast_structures.f90
- Source/CFAST/fire.f90
- Source/CFAST/initialization.f90
- Source/CFAST/input.f90
- Source/CFAST/output.f90
- Source/CFAST/outputspreadsheet.f90
> CFAST: Consolidate multiple fire position variables into a single definition

- Source/CFAST/fire.f90
- Source/CFAST/radiation.f90
- Source/CFAST/target.f90
- Utilities/Matlab/CFAST_validation_scatterplot_output_baseline.csv
Less than a 1% change in layer temperatures and surface temperature
> CFAST: Correct error in fire position for surface radiation calculation

- Source/CFAST/cfast.f90
- Source/CFAST/cfast_data.f90
- Source/CFAST/cfast_structures.f90
- Source/CFAST/flowhorizontal.f90
- Source/CFAST/flowvertical.f90
- Source/CFAST/initialization.f90
- Source/CFAST/input.f90
- Source/CFAST/output.f90
- Source/CFAST/outputspreadsheet.f90
- Source/CFAST/solve.f90
- Source/CFAST/utilities.f90
Took a mulligan and started over.
> CFAST: Rollback hvent changes to fix DASSL error resulting from last commit. 

- Source/CFAST/input.f90
> CFAST: Fix wall vent read when opening change is triggered by temperature or flux

- Source/Cedit/IO.vb
> CEdit: Correct read in of really old style vertical vents

- Source/CFAST/initialization.f90
- Source/CFAST/solve.f90
- Source/CFAST/target.f90
Still need to add printout and verify.
> CFAST: Add tenability calculation for narcotic gases and heat.  

- Source/CFAST/cfast.f90
- Source/CFAST/cfast_data.f90
- Source/CFAST/cfast_structures.f90
- Source/CFAST/fire.f90
- Source/CFAST/flowfan.f90
- Source/CFAST/flowhorizontal.f90
- Source/CFAST/flowvertical.f90
- Source/CFAST/input.f90
- Source/CFAST/new_input.f90
- Source/CFAST/output.f90
- Source/CFAST/outputspreadsheet.f90
- Source/CFAST/radiation.f90
- Source/CFAST/solve.f90
- Source/CFAST/utilities.f90
- Utilities/for_bundle/Bin/Data/Users_Guide_Example.cfast
Works for hand-converted standard example case.  Stills needs extensive testing before it's ready for release.
> CFAST: Initial implementation of namelist input.  

- Build/CFAST/makefile
add missing routine to makefile - fixes compile problem
> cfast build: fix makefile

- Source/CFAST/input.f90
- Source/CFAST/input_namelist.f90
- Source/CFAST/radiation.f90
- Source/CFAST/target.f90
Please kindly review the updates.
Update(2017_11_17): 1) Fix 2 bugs in target.f90, 2) Add new namelist group for disgnosis, 3) Incorporate changes in cfast_data, input, input_namelist, radiation, and target.f90 to facilitate simulation of verification case on CFAST radiation and target models.
Descriptions of the verification case and the associated results are included in below document.
[Verification case.docx](https://github.com/firemodels/cfast/files/1483036/Verification.case.docx)
> Verification cases for radiation and target routines and a word document including the results associated to the case

- Source/CFAST/input.f90
- Source/CFAST/input_namelist.f90
- Source/CFAST/radiation.f90
- Source/CFAST/target.f90
Code did not compile with missing variable references in radiation.f90.
> CFAST: Revert change from pull request 88810d4abd3f0874d9c1517ab1710c4da55a9e06. 

- Source/CFAST/target.f90
1) account for missing solid angles for targets when they are located at the surfaces
2) add absorptivity calculation
> Two changes are made to target.f90

- Utilities/Matlab/CFAST_verification_script.m
- Utilities/Matlab/scripts/radiativefluxes.m
- Utilities/Matlab/scripts/speciesmass.m
1) decouple radiation materials from speciesmass.m, 
2) create a separate .m for data process on radiation verification case(s), 
and 3) minor edits to CFAST_verification_script.m
> Re-organize updated contents

- Utilities/Matlab/scripts/radiativefluxes.m
Correct equation for hemispherical absorptivity and add comments for the absorptivity
> Correction to radiativefluxes.m

- Source/CFAST/fire.f90
New experiments show no effect.
> CFAST: Remove wall plume entrainment enhancement.

- Manuals/Bibliography/CFAST_refs.bib
- Manuals/Validation_Guide/Verification_Chapter.tex
A short verification exercise on AST calculation is added.
Cfastbot ran successfully on my computer.
> update reference and verification guide for AST calculation

- Source/CFAST/cfast_parameters.f90
This is for the MC simulations I'm doing. For some reason I'm exceeding 25 for a significant number of cases.
> mcb1:  increased number of max number of connections from 25 to 50

- Source/CFAST/input_namelist.f90
Two minor changes are made:
1) fix mechanical vent orientations
2) compartment referencing for vents associated with outside environment
An implementation for accounting the surface opened fraction will be provided once this PR is approved. Verification case is created. Simulation results are identical to analytical results.
> correction to input_namelist before adding calculation capability for surface opened fraction

- Source/CFAST/cfast_parameters.f90
- Source/CFAST/fire.f90
> CFAST: finish cleaning up constrained fire variable names.

- Source/CFAST/cfast_structures.f90
- Source/CFAST/initialization.f90
- Source/CFAST/output.f90
- Source/CFAST/outputspreadsheet.f90
- Source/CFAST/ssHeaders.f90
- Source/CFAST/target.f90
> CFAST: Fix initialization of spreadsheet output for smoke-triggered detectors

- Source/CFAST/cfast_interfaces.f90
- Source/CFAST/cfast_structures.f90
- Source/CFAST/input_namelist.f90
No change in V&V at this point
> CFAST: Begin adding less than notional HCN yield inputs. 

- Source/Cedit/Vent.vb
Still need to make CFAST correct for this is the file is edited outside of CEdit.
> CEdit: Fix in CEdit for Issue #1372 so that CEdit flags an error if the outside is the first compartment in a horizontal vent specification. 

- Source/CFAST/cfast.f90
- Source/CFAST/cfast_data.f90
- Source/CFAST/cfast_parameters.f90
- Source/CFAST/cfast_structures.f90
- Source/CFAST/flowhorizontal.f90
- Source/CFAST/initialization.f90
- Source/CFAST/input.f90
- Source/CFAST/input_namelist.f90
- Source/CFAST/output.f90
- Source/CFAST/outputdebug.f90
- Source/CFAST/outputspreadsheet.f90
- Source/CFAST/solve.f90
- Source/CFAST/ssHeaders.f90
- Source/CFAST/target.f90
- Source/CFAST/utilities.f90
Output is working but turned off for now. Need to transition V&V dataplot inputs to new layout.
> CFAST: New spreadsheet outputs per Issue #1298. 

- Manuals/Bibliography/commoncommands.tex
- Source/Cedit/IO.vb
Added &TAIL / and updated all versions to 7.5.0
> CEdit: Fix for Issue #1428. File write for some vents missing trailing /.

- Manuals/Monte_Carlo_Guide/CData_Ref.tex
This adds the &MHDR and &MRND inputs. Others still to come.
> CData: Documenting namelist inputs for CData

- Manuals/Monte_Carlo_Guide/CData_Guide_old.tex
- Manuals/Monte_Carlo_Guide/Examples/Simple.in
This reverts commit 7cfd011016ef870115e0ae6627f87cc7063094f6.
> Revert "CData Manual: changes to simple.in and Manual"

- Source/CFAST/outputspreadsheet.f90
This reverts commit 3aa09df966fde952490d85cc616fd30cffda0136.
> Revert "CFAST: Add some associated compartment conditions to device spreadsheet"

- Source/CFAST/cfast_structures.f90
- Source/CFAST/flowvertical.f90
- Source/CFAST/initialization.f90
- Source/CFAST/input_namelist.f90
Improves compartment temperature validation by about 1% on average.
> CFAST: Better initialization of exterior density for rooms above ground level. 

- Source/Cdata/write_inputfile.f90
Hello,
While working with CData, I found a small error when writing the output file.
I'll let you evaluate it.
> CData: replace MAC_TIME_STEP to MAX_TIME_STEP

- Source/CFAST/initialization.f90
A number of CData changes that got held up because of some problems with GitHub on PC
> CFAST: fix error in intitialization

- Source/CFAST/input_namelist.f90
…ents is the outside compartment
> fix problem with vent display - addresses issue 2167
